package org.expleo.TicketBookingJavaProject.model;

/*
 * Base User class
 * Represents common properties shared by all users
 * Sprint 1 - User Authentication Module
 */
public class User {

    // Unique identifier for user (auto-generated by database)
    protected int userId;
    
    // User's full name
    protected String name;
    
    // User's email address (used for login)
    protected String email;
    
    // User's phone number
    protected String phone;
    
    // User's password (used for authentication)
    protected String password;
    
    // User's role (Customer, Admin, Super Admin)
    protected String role;

    // Constructor to initialize all user fields
    public User(int userId, String name, String email, String phone, String password, String role) {
        this.userId = userId;
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.password = password;
        this.role = role;
    }

    // Getter and Setter methods for all fields
    public int getUserId() { return userId; }
    public void setUserId(int userId) { this.userId = userId; }
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }
    public String getPhone() { return phone; }
    public void setPhone(String phone) { this.phone = phone; }
    public String getPassword() { return password; }
    public void setPassword(String password) { this.password = password; }
    public String getRole() { return role; }
    public void setRole(String role) { this.role = role; }
}
